// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB72_AJfWQfh1kZbQ6N829aHYOCuLPXTlg',
    appId: '1:879820098286:web:6cd5291af85dd0cde381ff',
    messagingSenderId: '879820098286',
    projectId: 'fine-mobile-21acd',
    authDomain: 'fine-mobile-21acd.firebaseapp.com',
    storageBucket: 'fine-mobile-21acd.appspot.com',
    measurementId: 'G-0SZRB07ZNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcsDAajVRAd3BY4IDUbvSPz-YSARQxmeE',
    appId: '1:879820098286:android:4ca73cae7f56e83ce381ff',
    messagingSenderId: '879820098286',
    projectId: 'fine-mobile-21acd',
    storageBucket: 'fine-mobile-21acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2uGaWPI-MiCCx1EOMXVo3C_jFy0qIkoc',
    appId: '1:879820098286:ios:99123f84ab9d74dce381ff',
    messagingSenderId: '879820098286',
    projectId: 'fine-mobile-21acd',
    storageBucket: 'fine-mobile-21acd.appspot.com',
    iosClientId: '879820098286-kqctpm9jhlh49kop9r4fr4anahi2tnfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fineMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2uGaWPI-MiCCx1EOMXVo3C_jFy0qIkoc',
    appId: '1:879820098286:ios:99123f84ab9d74dce381ff',
    messagingSenderId: '879820098286',
    projectId: 'fine-mobile-21acd',
    storageBucket: 'fine-mobile-21acd.appspot.com',
    iosClientId: '879820098286-kqctpm9jhlh49kop9r4fr4anahi2tnfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fineMobile',
  );
}
